# Correzioni varie

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import os
import seaborn as sns

In [2]:
home_path = os.path.abspath(os.getcwd())
home_path

'C:\\Users\\Asus\\OneDrive\\Desktop\\NECST\\NL2\\FDAxEEG\\Dataset'

In [3]:
# per risalire dall'elemento del vettore al canale e banda basta sapere che se ci si trova in
# posizione i 
# i = 5*zona + banda
# zona = i mod 5 
# banda = i - i mod 5 * 5

p_val_int = np.array([0.5286,  0.4052,  0.3312,  0.1022,  0.2952,
                      0.0454,  0.0394,  0.0002,  0.0002,  0.2352,
                      0.4528,  0.5666,  0.1252,  0.1166,  0.7752,
                      0.6408,  0.5594,  0.6018,  0.0728,  0.0014,
                      0.3272,  0.2708,  0.1088,  0.2588,  0.0224,
                      0.1526,  0.9322,  0.3024,  0.2476,  0.0456,
                      0.0002,  0.0002,  0.0032,  0.0304,  0.4020])


p_val_norm = np.array([0.6820,  0.6504,  0.3608,  0.0118,  0.3410,
                    0.0002,  0.0012,  0.0002,  0.0002,  0.1232,
                    0.2532,  0.1022,  0.2542,  0.2148,  0.4512,
                    0.8926,  0.8962,  0.1468,  0.0526,  0.0016,
                    0.0204,  0.2140,  0.1850,  0.2968,  0.0410,
                    0.6058,  0.0620,  0.4740,  0.3442,  0.0656,
                    0.0002,  0.0002,  0.0062,  0.0164,  0.9768])

In [4]:
p_val_picco = np.array([0.7554,  0.2928,  0.1538,  0.0290,  0.2234,
                    0.0880,  0.1310,  0.0004,  0.0002,  0.9514,
                    0.2384,  0.4092,  0.7544,  0.0978,  0.7872,
                    0.9306,  0.5938,  0.4330,  0.0506,  0.0004,
                    0.3982,  0.7732,  0.2830,  0.1536,  0.0210,
                    0.2098,  0.9840,  0.9844,  0.7440,  0.0310,
                    0.0002,  0.0002,  0.0150,  0.0030,  0.1934])

In [5]:
func_p_val = pd.read_csv("p_val_functional.csv", sep = ',',index_col=False)
func_p_val = func_p_val.iloc[:,1:6]
func_p_val

0       1       2       3       4
0  0.3850  0.3450  0.1625  0.9750  0.1985
1  0.0000  0.0010  0.0005  0.0000  0.1255
2  0.0500  0.0165  0.0000  0.0365  0.2990
3  0.0620  0.1300  0.2050  0.0125  0.0060
4  0.0010  0.0525  0.0440  0.0590  0.0300
5  0.0395  0.2940  0.0820  0.2310  0.0490
6  0.0000  0.0000  0.0005  0.0075  0.0650

In [6]:
p_val_func = func_p_val.to_numpy()
p_val_func = p_val_func.flatten()
p_val_func

array([3.850e-01, 3.450e-01, 1.625e-01, 9.750e-01, 1.985e-01, 0.000e+00,
       1.000e-03, 5.000e-04, 0.000e+00, 1.255e-01, 5.000e-02, 1.650e-02,
       0.000e+00, 3.650e-02, 2.990e-01, 6.200e-02, 1.300e-01, 2.050e-01,
       1.250e-02, 6.000e-03, 1.000e-03, 5.250e-02, 4.400e-02, 5.900e-02,
       3.000e-02, 3.950e-02, 2.940e-01, 8.200e-02, 2.310e-01, 4.900e-02,
       0.000e+00, 0.000e+00, 5.000e-04, 7.500e-03, 6.500e-02])

In [7]:
from audioop import reverse

def reversed_enumerate(l):
    return zip(range(len(l)-1, -1, -1), reversed(l))

In [8]:
def Hochberg(p_val, alpha, m):
    order = p_val.argsort()
    p_val.sort()

    for i,p in reversed_enumerate(p_val):
        if(p <= (alpha/(m - i + 1))):
            break

        idx_reject = order[:(i+1)]

    return idx_reject

In [9]:
indxs = Hochberg(p_val_func, alpha = 0.05, m = 35)
indxs

array([ 8, 30, 31, 12,  5, 32,  7,  6, 20, 19], dtype=int64)

In [10]:
# matrice_picco_adhd = np.empty((555,indxs.size))
# matrice_picco_cont = np.empty((427,indxs.size))

# salvo le features di mio interesse
# della zona e banda di mio interesse devo avere vettore integrali di adhd e vettore integrali di control
for i,indx in enumerate(indxs):
    zona = indx//5
    banda = indx - indx//5*5

    # !!qui correggi, abbiamo già i dati, dobbiamo selezionare le colonne interessanti!!

    # picco_adhd, picco_cont = Picco(canale=zona+1,  banda=banda+1, home_path=home_path)
    # matrice_picco_adhd[:,i] = np.reshape(picco_adhd, (555,))
    # matrice_picco_cont[:,i] = np.reshape(picco_cont, (427,))
    
    print('Zona: '+str(zona)+'\tBanda: '+str(banda))


Zona: 1	Banda: 3
Zona: 6	Banda: 0
Zona: 6	Banda: 1
Zona: 2	Banda: 2
Zona: 1	Banda: 0
Zona: 6	Banda: 2
Zona: 1	Banda: 2
Zona: 1	Banda: 1
Zona: 4	Banda: 0
Zona: 3	Banda: 4


In [11]:
def Holm(p_val, alpha, m):
    order = p_val.argsort()
    p_val.sort()
    idx_reject=[]
    for i,p in enumerate(p_val):
        if(p <= (alpha/(m - i + 1))):
            idx_reject.append(order[i])

    return idx_reject

In [12]:
func_p_val = pd.read_csv("p_val_functional.csv", sep = ',',index_col=False)
func_p_val = func_p_val.iloc[:,1:6]
p_val_func = func_p_val.to_numpy()
p_val_func = p_val_func.flatten()

In [13]:
indxs = Holm(p_val_func, alpha = 0.05, m = 35)
indxs

[8, 30, 31, 12, 5, 32, 7, 6, 20]

In [14]:
# matrice_picco_adhd = np.empty((555,indxs.size))
# matrice_picco_cont = np.empty((427,indxs.size))

# salvo le features di mio interesse
# della zona e banda di mio interesse devo avere vettore integrali di adhd e vettore integrali di control
for i,indx in enumerate(indxs):
    zona = indx//5
    banda = indx - indx//5*5

    # !!qui correggi, abbiamo già i dati, dobbiamo selezionare le colonne interessanti!!

    # picco_adhd, picco_cont = Picco(canale=zona+1,  banda=banda+1, home_path=home_path)
    # matrice_picco_adhd[:,i] = np.reshape(picco_adhd, (555,))
    # matrice_picco_cont[:,i] = np.reshape(picco_cont, (427,))
    
    print('Zona: '+str(zona)+'\tBanda: '+str(banda))


Zona: 1	Banda: 3
Zona: 6	Banda: 0
Zona: 6	Banda: 1
Zona: 2	Banda: 2
Zona: 1	Banda: 0
Zona: 6	Banda: 2
Zona: 1	Banda: 2
Zona: 1	Banda: 1
Zona: 4	Banda: 0


In [15]:
p_val_feat=np.concatenate((p_val_int, p_val_norm, p_val_picco), axis=None)
p_val_feat

array([5.286e-01, 4.052e-01, 3.312e-01, 1.022e-01, 2.952e-01, 4.540e-02,
       3.940e-02, 2.000e-04, 2.000e-04, 2.352e-01, 4.528e-01, 5.666e-01,
       1.252e-01, 1.166e-01, 7.752e-01, 6.408e-01, 5.594e-01, 6.018e-01,
       7.280e-02, 1.400e-03, 3.272e-01, 2.708e-01, 1.088e-01, 2.588e-01,
       2.240e-02, 1.526e-01, 9.322e-01, 3.024e-01, 2.476e-01, 4.560e-02,
       2.000e-04, 2.000e-04, 3.200e-03, 3.040e-02, 4.020e-01, 6.820e-01,
       6.504e-01, 3.608e-01, 1.180e-02, 3.410e-01, 2.000e-04, 1.200e-03,
       2.000e-04, 2.000e-04, 1.232e-01, 2.532e-01, 1.022e-01, 2.542e-01,
       2.148e-01, 4.512e-01, 8.926e-01, 8.962e-01, 1.468e-01, 5.260e-02,
       1.600e-03, 2.040e-02, 2.140e-01, 1.850e-01, 2.968e-01, 4.100e-02,
       6.058e-01, 6.200e-02, 4.740e-01, 3.442e-01, 6.560e-02, 2.000e-04,
       2.000e-04, 6.200e-03, 1.640e-02, 9.768e-01, 7.554e-01, 2.928e-01,
       1.538e-01, 2.900e-02, 2.234e-01, 8.800e-02, 1.310e-01, 4.000e-04,
       2.000e-04, 9.514e-01, 2.384e-01, 4.092e-01, 

In [16]:
indxs = Hochberg(p_val_feat, alpha = 0.05, m = 35*3)
indxs

array([ 78,  31,  30,  65,  40,  42,   8,  66,  43, 101,   7, 100,  77,
        89,  41], dtype=int64)

In [17]:
# matrice_picco_adhd = np.empty((555,indxs.size))
# matrice_picco_cont = np.empty((427,indxs.size))

# salvo le features di mio interesse
# della zona e banda di mio interesse devo avere vettore integrali di adhd e vettore integrali di control
for i,indx in enumerate(indxs):
    feature = indx//35
    zona = (indx-35*feature)//5
    banda = (indx-35*feature) - (indx-35*feature)//5*5
    
    feat=['Int', 'Norm', 'Picco']
    # !!qui correggi, abbiamo già i dati, dobbiamo selezionare le colonne interessanti!!

    # picco_adhd, picco_cont = Picco(canale=zona+1,  banda=banda+1, home_path=home_path)
    # matrice_picco_adhd[:,i] = np.reshape(picco_adhd, (555,))
    # matrice_picco_cont[:,i] = np.reshape(picco_cont, (427,))
    
    print('Feature: ' + feat[feature]+'\tZona: '+str(zona)+'\tBanda: '+str(banda))

Feature: Picco	Zona: 1	Banda: 3
Feature: Int	Zona: 6	Banda: 1
Feature: Int	Zona: 6	Banda: 0
Feature: Norm	Zona: 6	Banda: 0
Feature: Norm	Zona: 1	Banda: 0
Feature: Norm	Zona: 1	Banda: 2
Feature: Int	Zona: 1	Banda: 3
Feature: Norm	Zona: 6	Banda: 1
Feature: Norm	Zona: 1	Banda: 3
Feature: Picco	Zona: 6	Banda: 1
Feature: Int	Zona: 1	Banda: 2
Feature: Picco	Zona: 6	Banda: 0
Feature: Picco	Zona: 1	Banda: 2
Feature: Picco	Zona: 3	Banda: 4
Feature: Norm	Zona: 1	Banda: 1


In [18]:
p_val_feat=np.concatenate((p_val_int, p_val_norm, p_val_picco), axis=None)

In [19]:
indxs = Holm(p_val_feat, alpha = 0.05, m = 35*3)
indxs

[78, 31, 30, 65, 40, 42, 8, 66, 43, 101, 7, 100, 77, 89]

In [20]:
# matrice_picco_adhd = np.empty((555,indxs.size))
# matrice_picco_cont = np.empty((427,indxs.size))

# salvo le features di mio interesse
# della zona e banda di mio interesse devo avere vettore integrali di adhd e vettore integrali di control
for i,indx in enumerate(indxs):
    feature = indx//35
    zona = (indx-35*feature)//5
    banda = (indx-35*feature) - (indx-35*feature)//5*5
    
    feat=['Int', 'Norm', 'Picco']
    # !!qui correggi, abbiamo già i dati, dobbiamo selezionare le colonne interessanti!!

    # picco_adhd, picco_cont = Picco(canale=zona+1,  banda=banda+1, home_path=home_path)
    # matrice_picco_adhd[:,i] = np.reshape(picco_adhd, (555,))
    # matrice_picco_cont[:,i] = np.reshape(picco_cont, (427,))
    
    print('Feature: ' + feat[feature]+'\tZona: '+str(zona)+'\tBanda: '+str(banda))

Feature: Picco	Zona: 1	Banda: 3
Feature: Int	Zona: 6	Banda: 1
Feature: Int	Zona: 6	Banda: 0
Feature: Norm	Zona: 6	Banda: 0
Feature: Norm	Zona: 1	Banda: 0
Feature: Norm	Zona: 1	Banda: 2
Feature: Int	Zona: 1	Banda: 3
Feature: Norm	Zona: 6	Banda: 1
Feature: Norm	Zona: 1	Banda: 3
Feature: Picco	Zona: 6	Banda: 1
Feature: Int	Zona: 1	Banda: 2
Feature: Picco	Zona: 6	Banda: 0
Feature: Picco	Zona: 1	Banda: 2
Feature: Picco	Zona: 3	Banda: 4
